# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

# Create a bot to automatically pull requests
version: 2

updates:

  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

    open-pull-requests-limit: 10

    labels:
      - "dependencies"
      - "python"

    groups:
      django:
        patterns:
          - "django*"
          - "crispy-*"
          - "daphne"
          - "channels*"
          - "asgiref"
          - "djangorestframework"
      aws:
        patterns:
          - "boto3"
          - "botocore"
          - "s3transfer"
      celery:
        patterns:
          - "celery"
          - "kombu"
          - "billiard"
          - "vine"
      database:
        patterns:
          - "pymongo"
          - "psycopg*"
          - "redis"
      data:
        patterns:
          - "numpy"
          - "pandas"
          - "biopython"
          - "openpyxl"
          - "xlrd"
          - "XlsxWriter"
      testing:
        patterns:
          - "pytest*"
          - "selenium"
          - "mock"
      all-others:
        patterns:
          - "*"

  # Dockerfile base image updates
  - package-ecosystem: "docker"
    directory: "/deployment/web/"
    schedule:
      interval: "weekly"

    labels:
      - "docker"

  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

    labels:
      - "github-actions"