[pytest]

# 'r' shows extra test summary info
# 'a' shows all except passed tests
addopts = -ra

DJANGO_SETTINGS_MODULE = src.main_config.settings.all

python_files =
    tests.py
    test_*.py
    *_tests.py

# Target test files in the playwright directory
testpaths =
    test/playwright