FROM python:3.12.7-slim-bookworm

ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH=/copo

WORKDIR /copo
COPY . .

# Install test dependencies
COPY ./requirements/ /tmp/requirements/

RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    python3-dev \
    libxml2-dev \
    libpq-dev \
    curl \
    wget \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip \
    && pip install --use-deprecated=legacy-resolver -r /tmp/requirements/dev.txt \
    && pip install pytest pytest-playwright

# Install Playwright browsers
RUN playwright install --with-deps

# Default command for Playwright test container
CMD ["pytest", "test/playwright"]
