FROM ubuntu:24.04

ENV PYTHONUNBUFFERED=1

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    default-jre \
    git \
    net-tools \
    vim \
    nano \ 
    libxml2-dev \
    python3 \
    build-essential \
    make \
    gcc \
    locales \
    python3-dev \
    python3-venv \
    python3-pip \
    python-is-python3 \
    ruby-dev \
    rubygems \
    poppler-utils \
    wget curl unzip less tcpdump iputils-ping vim && \
    gem install sass && \
    pip install --upgrade pip && \
    apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*

# Create virtual environment
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY ./requirements/ /tmp/requirements/
RUN pip install --use-deprecated=legacy-resolver -r /tmp/requirements/dev.txt

#RUN mkdir /copo
#RUN mkdir /code

WORKDIR /copo
#COPY . /code/

RUN mkdir -p /copo/tools/reposit/ena_cli && \
    wget -O /copo/tools/reposit/ena_cli/webin-cli.jar https://github.com/enasequence/webin-cli/releases/download/9.0.3/webin-cli-9.0.3.jar

# add aspera client to path
COPY ./shared_tools/reposit/.aspera/ /root/.aspera/
ENV PATH="/root/.aspera/cli/bin:$PATH"

# Install VSCode
RUN curl -fsSL https://code-server.dev/install.sh | sh

#RUN wget -q -O- https://aka.ms/install-vscode-server/setup.sh | sh

# Note that since venv is installed at /opt/venv then, daphne is installed at /opt/venv/bin/daphne not /usr/local/bin/daphne
#ENTRYPOINT ["bash","-c","rsync -avhW --no-compress --progress /code/ /copo/ &&  rm -rf /code/ && python manage.py migrate && python manage.py social_accounts && python manage.py setup_groups && python manage.py setup_schemas && python manage.py createcachetable && supervisord -c celery.conf && supervisorctl -c celery.conf start all && /opt/venv/bin/daphne -b 0.0.0.0 -p 8000 web.asgi:application"]

#wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sh /dev/stdin &&

