# Generated by Django 5.1.1 on 2026-03-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copo_core', '0026_merge_20260202_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='material_icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
