# Generated by Django 5.1.1 on 2026-03-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copo_core', '0027_add_material_icon_to_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletype',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
