# Generated by Django 5.1.15 on 2026-06-30 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copo_core', '0018_profiletype_post_delete_action'),
        ('copo_core', '0028_increase_profiletype_description_length'),
    ]

    operations = [
    ]
