# Generated by Django 6.0.7 on 2026-08-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copo_core', '0029_userrepositorycredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
