# Generated by Django 6.1 on 2026-09-30 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copo_core', '0029_merge_20260630_1744'),
        ('copo_core', '0030_banner_expires_at'),
    ]

    operations = [
    ]
